// Contraction -> full form expansion table (PLAN.md §7.1.2).
// Ambiguous contractions branch into multiple expansions (he's -> he is / he has);
// normalize() explores every branch and returns the union as a Set.
export const CONTRACTIONS: Record<string, readonly string[]> = {
  "don't": ['do not'],
  "won't": ['will not'],
  "can't": ['cannot'],
  "let's": ['let us'],
  "isn't": ['is not'],
  "aren't": ['are not'],
  "wasn't": ['was not'],
  "weren't": ['were not'],
  "doesn't": ['does not'],
  "didn't": ['did not'],
  "haven't": ['have not'],
  "hasn't": ['has not'],
  "hadn't": ['had not'],
  "wouldn't": ['would not'],
  "shouldn't": ['should not'],
  "couldn't": ['could not'],
  "mustn't": ['must not'],
  "i'm": ['i am'],
  "you're": ['you are'],
  "we're": ['we are'],
  "they're": ['they are'],
  "i'll": ['i will'],
  "you'll": ['you will'],
  "he'll": ['he will'],
  "she'll": ['she will'],
  "we'll": ['we will'],
  "they'll": ['they will'],
  "it'll": ['it will'],
  "i've": ['i have'],
  "you've": ['you have'],
  "we've": ['we have'],
  "they've": ['they have'],
  // Ambiguous 's: pronoun/wh-word + is|has.
  "he's": ['he is', 'he has'],
  "she's": ['she is', 'she has'],
  "it's": ['it is', 'it has'],
  "what's": ['what is', 'what has'],
  "that's": ['that is', 'that has'],
  "there's": ['there is', 'there has'],
  "here's": ['here is', 'here has'],
  "who's": ['who is', 'who has'],
  // Ambiguous 'd: pronoun + would|had.
  "i'd": ['i would', 'i had'],
  "you'd": ['you would', 'you had'],
  "he'd": ['he would', 'he had'],
  "she'd": ['she would', 'she had'],
  "we'd": ['we would', 'we had'],
  "they'd": ['they would', 'they had'],
};
